remote_theme: just-the-docs/just-the-docs
logo: "./assets/npmrd_logo.png"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

baseurl: "/npmrd_cross_domain_integration_docs"

# Footer last edited timestamp
last_edit_timestamp: true 
